/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arabic.ocr;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Mohamed
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private JFileChooser chooser;
    ProcessImage processiaImage;
    Thread thread;

    public MainFrame() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Arabic OCR");
        jtaExtractedText.setAutoscrolls(true);

        jbtnLoadImage.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                JFileChooser fileChooser = new JFileChooser();
                FileNameExtensionFilter filter = new FileNameExtensionFilter(
                        "JPG || PNG || BMB Images", "jpg", "png", "bmb");
                fileChooser.setFileFilter(filter);
                if (fileChooser.showOpenDialog(null)
                        == JFileChooser.APPROVE_OPTION) {
                    File ImageFile = fileChooser.getSelectedFile();
                    processiaImage = new ProcessImage(ImageFile);
                }
            }
        });

        jbtnExtractText.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                thread = new Thread(new Runnable() {

                    @Override
                    public void run() {
                        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("This may take a few seconds"));
                        jtaExtractedText.setText("");
                        jtaExtractedText.append(processiaImage.getResult());
                        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Extracted text"));
                    }
                });
                thread.start();

            }
        });

        jbtnSaveText.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                thread = new Thread(new Runnable() {

                    @Override
                    public void run() {
                        String extractedText = jtaExtractedText.getText();
                        try {
                            JFileChooser fileChooser = new JFileChooser();
                            FileNameExtensionFilter filter = new FileNameExtensionFilter(
                                    "Text: txt", "txt");
                            fileChooser.setFileFilter(filter);
                            if (fileChooser.showSaveDialog(null)
                                    == JFileChooser.APPROVE_OPTION) {
                                PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter(fileChooser.getSelectedFile().getPath()+".txt"/*"D:\\ExtractedText.txt"*/)));
                                out.append(extractedText);
                                out.close();
                                //jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("file has been saved to D:\\ExtractedText.txt"));
                            }

//                            PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter("D:\\ExtractedText.txt")));
//                            out.append(extractedText);
//                            out.close();
                            //jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("file has been saved to D:\\ExtractedText.txt"));
                        } catch (IOException ex) {
                            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }
                });
                thread.start();

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnLoadImage = new javax.swing.JButton();
        jbtnExtractText = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaExtractedText = new javax.swing.JTextArea();
        jbtnExtractText1 = new javax.swing.JButton();
        jbtnSaveText = new javax.swing.JButton();
        jbtnSaveText1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnLoadImage.setMnemonic('l');
        jbtnLoadImage.setText("Load image");

        jbtnExtractText.setMnemonic('e');
        jbtnExtractText.setText("Extract text");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Extracted text"));

        jtaExtractedText.setColumns(20);
        jtaExtractedText.setRows(5);
        jScrollPane1.setViewportView(jtaExtractedText);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jbtnExtractText1.setMnemonic('x');
        jbtnExtractText1.setText("Exit");
        jbtnExtractText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExtractText1ActionPerformed(evt);
            }
        });

        jbtnSaveText.setMnemonic('e');
        jbtnSaveText.setText("Save text");

        jbtnSaveText1.setMnemonic('e');
        jbtnSaveText1.setText("About");
        jbtnSaveText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveText1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnLoadImage, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExtractText, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExtractText1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSaveText, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSaveText1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jbtnLoadImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnExtractText, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnSaveText, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnSaveText1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jbtnExtractText1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnExtractText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExtractText1ActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_jbtnExtractText1ActionPerformed

    private void jbtnSaveText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveText1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "All rights are reserved to Mohamed Wael\n"
                + "Faculty of computers and information sciences, Mansoura university\n"
                + "Computer science department", "copyright ©", WIDTH);
    }//GEN-LAST:event_jbtnSaveText1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnExtractText;
    private javax.swing.JButton jbtnExtractText1;
    private javax.swing.JButton jbtnLoadImage;
    private javax.swing.JButton jbtnSaveText;
    private javax.swing.JButton jbtnSaveText1;
    private javax.swing.JTextArea jtaExtractedText;
    // End of variables declaration//GEN-END:variables
}
